DELETE http://localhost:4000/api/tickets/c315a7cb-1c93-44b3-8cbe-abb8226b6dd3 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmE3NzA0N2Y0NTk3N2NmZDBjMTgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTk0MzM0NjksImV4cCI6MTcxOTQzNzA2OX0.yg7eAtN14s-jI3Q_oytQkhjI0r9nDIGReZiMnNvMSxk